language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"
sudo: false
cache:
  directories:
    - node_modules
script:
  - "npm run test"
  - "npm run lint"

after_script: "npm install coveralls2.10.0 && cat ./coverage/lcov.info | coveralls"